### ISSUE TITLE
Program exits without downloading files.

### ISSUE THREAD

**Issue by Devansh-bit** [oSumAtrIX/DownOnSpot#11]
**Describe the bug**
Program exists without downloading music and without any error/indication of something going wrong

**Expected behavior**
Downloading of files should start

**Screenshots**
![image](https://user-images.githubusercontent.com/67866743/144763158-f686288a-a912-424f-a3aa-8bf5e65abb67.png)

**Desktop (please complete the following information):**
- OS: Windows 10

**Additional context**
Adding a debug option should be helpful for future issues

**Comment by oSumAtrIX** [comment]
Did you pull the latest commits hefore trying to build again?

**Comment by Devansh-bit** [comment]
Yep I did and I figured that I didn't put in client ID and secret. Filling that in fixed the issue.
