### ISSUE TITLE
silent failure to download

### ISSUE THREAD

**Issue by VincentGijsen** [oSumAtrIX/DownOnSpot#12]
**Describe the bug**
after compilation compilation, it failes silently...  
it is compiled,
then executing: 
```bash-3.2$ ./down_on_spot https://open.spotify.com/playlist/6bYg4fYfP0TNNKpOqLDRSR

Settings successfully loaded.
Continuing with spotify account: <RED>.
Login succeeded.
```

Nothing happens, no download, am i using it wrong, or is ClientID / Secret to be filled-out, other than standard?

```
settings:

{
  "username": "<RED>",
  "password": "<RED>",
  "client_id": "client_id",
  "client_secret": "secret",
  "refresh_ui_seconds": 1,
  "downloader": {
    "concurrent_downloads": 4,
    "quality": "Q320",
    "path": "downloads",
    "filename_template": "%artist% - %title%",
    "id3v24": true,
    "convert_to_mp3": false,
    "separator": ", "
  }
}
```

used brew install lame to get `lame mp3` on my system.

**To Reproduce**
```
bash-3.2$ ./down_on_spot https://open.spotify.com/playlist/6bYg4fYfP0TNNKpOqLDRSR
```

**Expected behavior**
a download, progress or failue, instead, jumps straight to terminal

- OS: (MacOsx Darwin <RED> 19.6.0 Darwin Kernel Version 19.6.0: Thu Nov 11 20:02:32 PST 2021; root:xnu-6153.141.49~1/RELEASE_X86_64 x86_64), 
- Basically old Macbook Air

**Comment by VincentGijsen** [comment]
adding some debug-lines, i have not the error: ```Error: invalid_client: Invalid client```, do i presume correctly that i need a Devaccount from spotify?

**Comment by benjick** [comment]
> adding dev api reqs, solved the issue;

How do I get these?

**Comment by VincentGijsen** [comment]
Goto developer.Spotify.com, sign in with your Spotify credentials, create new app, and voilà. It gives you api I’d and key.

**Comment by ckcr4lyf** [comment]
Observing the "Silent failure" issue as well, no clear indication in the TUI, and the file is made (`.mp3`). But it is impossibly small / incomplete.

Kinda related - https://github.com/oSumAtrIX/DownOnSpot/issues/19#issuecomment-1029105723

**Comment by oSumAtrIX** [comment]
Moving to #53
