### ISSUE TITLE
Better SSH Tutorial

### ISSUE THREAD

**Issue by Edison12300** [oSumAtrIX/DownOnSpot#17]
Hi, is there a better SSH tutorial?
Still doesn't know what to do after reading the current tutorial.

**Comment by oSumAtrIX** [comment]
You need to use the SSH key in order to clone the repository. For that, you need to download it & configure it in your SSH config. Cargo will then use the ssh-agent to clone the private repository over SSH via the ssh-agent.

**Comment by Edison12300** [comment]
I see. And this is for the free account?
What if I want to use a premium account?

**Comment by Edison12300** [comment]
Also, what is this error?
![螢幕擷取畫面 2022-01-31 024450](https://user-images.githubusercontent.com/71360570/151712992-9fddf3ec-b217-41d2-be01-a7551b817eb9.png)

**Comment by oSumAtrIX** [comment]
> I see. And this is for the free account? What if I want to use a premium account?

The repository which you can access via the private key allows the use of free accounts. If you do not need that, because you have a premium account, you can remove the git dependency from `cargo.toml` as said in the README. Cargo will then use the official crate which requires you to have a premium account.

> Also, what is this error? ![螢幕擷取畫面 2022-01-31 024450](https://user-images.githubusercontent.com/71360570/151712992-9fddf3ec-b217-41d2-be01-a7551b817eb9.png)

I fixed this error in the latest commits, Pull the changes and try to build.

**Comment by Edison12300** [comment]
> The repository which you can access via the private key allows the use of free accounts. If you do not need that, because you have a premium account, you can remove the git dependency from `cargo.toml` as said in the README. Cargo will then use the official crate which requires you to have a premium account.

Do I just delete the whole line, or do I need to replace it with something else?
Also, how do I run it?

**Comment by oSumAtrIX** [comment]
For that, please follow the instructions in the readme.

**Comment by Edison12300** [comment]
Yeah, but I delete the line, I can't build it.

**Comment by oSumAtrIX** [comment]
> Yeah, but I delete the line, I can't build it.

You are not supposed to delete the line. Check #13

**Comment by Edison12300** [comment]
Not sure if I'm doing it right, but I can't run the down_on_spot.exe command.

**Comment by oSumAtrIX** [comment]
I can't help you without any errors or logs.

**Comment by Edison12300** [comment]
It just says bash: down_on_spot.exe: command not found

**Comment by oSumAtrIX** [comment]
Please refer to your terminal on how to run executables. This is not an issue with DownOnSpot.

**Comment by Edison12300** [comment]
Got that worked out, but how do I add my credentials?

**Comment by oSumAtrIX** [comment]
> Got that worked out, but how do I add my credentials?

https://github.com/oSumAtrIX/DownOnSpot/blob/bd3816c16f0c98edb1b8a607c69f974d5e89f808/src/settings.rs#L33

**Comment by Edison12300** [comment]
Sorry, but I don't understand that.

**Comment by Edison12300** [comment]
I got it working. Thanks for all the help, appreciated it.
Hope my questions didn't waste too much of your time!
