### ISSUE TITLE
Audio Key Error

### ISSUE THREAD

**Issue by Puncia** [oSumAtrIX/DownOnSpot#20]
The program exits without downloading anything, giving the message "Audio Key Error"

![image](https://user-images.githubusercontent.com/4633311/152725682-1ef62ec6-77f3-4d23-92ad-ca53ff8baf2e.png)

It doesn't matter if I give a track link or if I use the search function. My config file is identical to the one automatically generated, except for the account credentials (free account) and `client_id` and `client_secret`. I also tried to create a new Spotify App from the dashboard and using different client credentials but the issue persists.

**Comment by oSumAtrIX** [comment]
Did you compile with the free-librespot crate?

**Comment by oSumAtrIX** [comment]
Free accounts are limited to download up to 160kbit/s as said in the README. Make sure you set that.

**Comment by Puncia** [comment]
Right, I totally missed it, changing my config accordingly solved the issue.
