### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by hippotread** [oSumAtrIX/DownOnSpot#22]
Built and ran the executable. Got the expected message saying that the configuration file was generated but it's not found in the directory where I'm running the exe. Where would it be located at?

![image](https://user-images.githubusercontent.com/67121472/153733249-dec81e0a-8704-4527-9fea-94d79b04364a.png)

**Comment by oSumAtrIX** [comment]
Depends https://github.com/oSumAtrIX/DownOnSpot/blob/bd3816c16f0c98edb1b8a607c69f974d5e89f808/src/settings.rs#L29
