### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by darw00d** [oSumAtrIX/DownOnSpot#25]
**Describe the bug**
Attempting to build but encounter issue with `steam-cipher` version within `crates.io
`
```
$ cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `stream-cipher = "^0.3"`
candidate versions found which didn't match: 0.99.99, 0.7.1, 0.6.0, ...
location searched: crates.io index
required by package `aes-ctr v0.3.0`
    ... which satisfies dependency `aes-ctr = "^0.3"` of package `librespot-audio v0.1.5`
    ... which satisfies dependency `librespot-audio = "^0.1.5"` of package `librespot v0.1.5`
    ... which satisfies dependency `librespot = "^0.1.5"` of package `down_on_spot v0.2.0 
```

**To Reproduce**

Using Rust `cargo 1.62.0-nightly (f63f23ff1 2022-04-28)`
Have Spotify Premium so removed free-librespot line and set to `librespot = "0.1.5"` in cargo.toml
Run `cargo build --release` in Git Bash dir containing clone of DownOnSpot

**Expected behavior**
Expected _`down_on_spot.exe`_ to compile successfully so  I can set config for spotify account and try downloading a playlist.

**Screenshots**
Error output added above

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
Not sure whether there's additional config I've missed or if this is someting inherant with newer versions of rust 
Hopefully I've not missed any additional info needed.

**Comment by oSumAtrIX** [comment]
Use the latest version of the librespot crate: https://crates.io/crates/librespot/
