### ISSUE TITLE
Allow Building without mp3 support

### ISSUE THREAD

**Issue by DavidBuchanan314** [oSumAtrIX/DownOnSpot#27]
**Is your feature request related to a problem? Please describe.**
Installing the libmp3lame dependency on macOS looks annoying, and I don't plan on using the mp3 feature anyway, so it'd be nice to not include it in the build process.

**Describe the solution you'd like**
An option to build without mp3 conversion support, excluding mp3lame

**Comment by grantHarris** [comment]
Yeah `brew install lame` doesn't seem to actually install the library on mac and there's not a ton of info online.

**Comment by DavidBuchanan314** [comment]
btw, I was able to compile it in the end by just deleting all the mp3-related code. But I was in a rush so I didn't try to implement it as an actual feature

**Comment by grantHarris** [comment]
I ended up just building it in a docker container and bypassed running it directly on the Mac OS. That said, I'd support a build that doesn't require that dependancy (I'm using it with Traktor which can read ogg so I'd rather not reencode anyways)

**Comment by i-am-the-slime** [comment]
How do I get the library, though?

**Comment by abuisman** [comment]
Ah, I got it working by doing this: 

`export LIBRARY_PATH="/usr/local/lib"`
`ln /opt/homebrew/opt/lame/lib/libmp3lame.dylib "$LIBRARY_PATH/libmp3lame.dylib"`

**Comment by mossepso** [comment]
```
export LIBRARY_PATH="/usr/local/lib"
ln /opt/homebrew/opt/lame/lib/libmp3lame.dylib "$LIBRARY_PATH/libmp3lame.dylib"
```
