### ISSUE TITLE
Cannot Build Application [invalid number of arguments]

### ISSUE THREAD

**Issue by ohitstom** [oSumAtrIX/DownOnSpot#37]
**To Reproduce**
clone repo, install rust-nightly, install visual studio and c++ dependencies.
Attempt to build.

**Screenshots**
![image](https://user-images.githubusercontent.com/22730962/182827901-e24e641b-3228-4e28-b047-b29f4a1a7f3e.png)
![image](https://user-images.githubusercontent.com/22730962/182827899-a893dc29-24bf-42da-b3f3-e3d3248318b7.png)

**Desktop (please complete the following information):**

- OS: Win10

**Comment by oSumAtrIX** [comment]
Please follow the installation instructions from the README.

**Comment by ohitstom** [comment]
Updated.

**Comment by oSumAtrIX** [comment]
Please create a new issue with very detailed reproduction step

**Comment by ohitstom** [comment]
How can it be more detailed than that, i followed your guide on the readme to a T.

**Comment by oSumAtrIX** [comment]
Your reproduction steps do not include detailed instructions on what you edited in which toml for example.
