### ISSUE TITLE
Nothing visible happens after launch.

### ISSUE THREAD

**Issue by xFELAx** [oSumAtrIX/DownOnSpot#41]
**Describe the bug**
I configured everything as it was described in instruction and launched .\down_on_spot.exe command then nothing happened.
(screenshot 3.)

**To Reproduce**

1. Clone the repository
2. Change librespot in Cargo.toml like in instruction because i have premium account (screenshot 1.)
3. Build project
4. Run .\down_on_spot.exe
5. Change settings.rs (screenshot 4.)

**Expected behavior**
Any information should be displayed because I don't know what is happening.

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/35076278/189532539-b3d3acdc-d482-4c2c-a88a-389329a5cd3c.png)

2.

![image](https://user-images.githubusercontent.com/35076278/189532379-1662b0b1-2ee5-49b1-befa-8bb8e307a224.png)

3.

![image](https://user-images.githubusercontent.com/35076278/189532409-fd15933f-a448-4e20-938b-9420f69898af.png)

4.
![image](https://user-images.githubusercontent.com/35076278/189532785-36902fd9-3b46-45e3-915e-a8a651363cba.png)

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
Powershell 7

**Comment by oSumAtrIX** [comment]
Do not add the credentials in the source code, a config file in %appdata5/downonspot is being created, where you have to fill your credentials.
