### ISSUE TITLE
Project depends on the GitHub repository that doesn't exist

### ISSUE THREAD

**Issue by yurivict** [oSumAtrIX/DownOnSpot#46]
**Describe the bug**
This line points to the project that doesn't exist:
DownOnSpot/Cargo.toml:librespot = { git = "ssh://git@github.com/oSumAtrIX/free-librespot.git" }

**Comment by henk23** [comment]
Hey @yurivict please read the readme.md very carefully word by word.
You need a special private key to access that repo.
