### ISSUE TITLE
free-librespot removed and not accessible with SSH key 

### ISSUE THREAD

**Issue by nimagp** [oSumAtrIX/DownOnSpot#47]
**Describe the bug**
Apparently free-librespot is removed or the private key doesn't have access to it. Error `fatal: repository 'git@github.com/oSumAtrIX/free-librespot.git' does not exist` occurs 
**To Reproduce**

1. Download and set SSH key (tried both ssh-agent and config file)
2. Check authentication with `ssh -T git@github.com`(successful) 
3. `git clone git@github.com/oSumAtrIX/free-librespot.git`
4. Git fails to fetch repository 

**Expected behavior**
Repository being cloned. 
**Screenshots**
![IMG_20230116_125028](https://user-images.githubusercontent.com/71447191/212643652-0faeb810-53ca-41cc-a52a-d567a8e6390c.jpg)

**Desktop (please complete the following information):**

- OS: Linux ARM (Termux)

**Additional context**

**Comment by oSumAtrIX** [comment]
The key should work:

**Comment by oSumAtrIX** [comment]
The key should work:

![image](https://user-images.githubusercontent.com/13122796/212707094-6f9872ea-b5ef-4c36-b2e8-0776550081e8.png)

**Comment by nimagp** [comment]
> The key should work:
> 
> ![image](https://user-images.githubusercontent.com/13122796/212707094-6f9872ea-b5ef-4c36-b2e8-0776550081e8.png)

Can you please test it yourself?
This is the result with my system:
![image](https://user-images.githubusercontent.com/71447191/212748943-c4e83460-12e5-488e-ac35-7570cf63b3d5.png)

**Comment by oSumAtrIX** [comment]
Not sure, the repository exists.

**Comment by nimagp** [comment]
> Not sure, the repository exists.
It was a typo in the command 😅
Can I compile spotifyd with this fork?
How should you get authentication tokens?

**Comment by oSumAtrIX** [comment]
spotifyd is available on crates.io

**Comment by nimagp** [comment]
> spotifyd is available publicly on github.com.

Thanks
But I mean Spotify tokens.
