### ISSUE TITLE
MacOS Compilation is Broken

### ISSUE THREAD

**Issue by joamjoamjoam** [oSumAtrIX/DownOnSpot#51]
**Describe the bug**
Compiling DownOnSpot on MacOS fails due to an import error for std::os::windows

**To Reproduce**
Compile on MacOS

**Expected behavior**
Compilation is successful

**Desktop (please complete the following information):**

- OS: MacOS Ventura

**Additional context**
This import was introduced in aa3c09b112a0d17e8cf74f4b7ddc815143229880

**Comment by oSumAtrIX** [comment]
I can't find it:

![image](https://github.com/oSumAtrIX/DownOnSpot/assets/13122796/5e48a41a-91d0-4321-9fec-af886936364c)

**Comment by joamjoamjoam** [comment]
Its in a std block search os::windows. I also linked the commit where the changes were made.

**Comment by LostXOR** [comment]
This also breaks compilation on Linux.

**Comment by joamjoamjoam** [comment]
Removing the os::windows::process use declaration worked for me.

**Comment by oSumAtrIX** [comment]
From my tests there is something wrong with the long deprecated crate aspotify. Its successor rspotify is what I am currently migrating to. Premium users are not affected.

**Comment by onny** [comment]
I removed the `os:windows` line and got downonspot to compile. Downloading (with premium) fails
```
Settings successfully loaded.
Continuing with spotify account: username.
Login failed, possibly due to invalid credentials or settings: Error: Unknown error { Network is unreachable (os error 101) }
```
