### ISSUE TITLE
not manage to start download with `down_on_spot.exe`

### ISSUE THREAD

**Issue by AKtomik** [oSumAtrIX/DownOnSpot#53]
Hi !
I make the whole instalation uing README guide. The web app is ready, tokens writtens in `settings.json` (on APPDATA ; im on windows).
So, now, i try. Login sucessfull ! Well, cool !
**But when I try to add anything more (link), that not working**. Like if i just didn't send link, and no more reaction (no message, nor download starting)
See :
![image](https://github.com/oSumAtrIX/DownOnSpot/assets/97125853/572963f3-688a-4303-bc49-22b946ba5a92)

So, what's could be wrong ?
Its probably a fail on my side, but where ? In the spotify dev app ?
Or in the `.\down_on_spot.exe` link argument syntaxe ? **Could you send me just a screen of a working download command ?** (search everywhere, but don't find one)

**Thank in advance for your help**, and thank for your work on this app !

**Comment by migo1271** [comment]
Same issue on my side. With latest version nothing happens. 0.2.3 worked as expected.
Windows 11 with cargo 1.72.0-nightly (03bc66b55 2023-06-23)

**Comment by AKtomik** [comment]
did you acheeve to make it working before ?

**Comment by migo1271** [comment]
Yes, it worked like a charm.

**Comment by AKtomik** [comment]
Since when its not working ? (time/action/MAJ)

**Comment by migo1271** [comment]
I used it the last time in April this year.

**Comment by oSumAtrIX** [comment]
Currently you need premium. There is an issue with the now deprecated crate aspotify which has ro be replaced with rspotify.

**Comment by migo1271** [comment]
Strange. I am using Spotify Premium.

**Comment by migo1271** [comment]
I think I found a work-around: remove the [/int-xx/](url) portion in the URL. Then it should work again.

**Comment by oSumAtrIX** [comment]
Which URL?

**Comment by AKtomik** [comment]
> I think I found a work-around: remove the [/int-xx/](url) portion in the URL. Then it should work again.

Change nothing, and removing portion after the `?` too.
![image](https://github.com/oSumAtrIX/DownOnSpot/assets/97125853/0e5c57e4-293c-4fc5-9a60-7faac3cf6f06)

**Comment by migo1271** [comment]
You don't need to remove the part after the "?".
This doesn't work: 
`down_on_spot.exe https://open.spotify.com/intl-de/track/2fXKyAyPrEa24c6PJyqznF?si=f35a831ebf024ec9`
But this does:
`down_on_spot.exe https://open.spotify.com/track/2fXKyAyPrEa24c6PJyqznF?si=f35a831ebf024ec9`
Do you have a premium account?
Your link works for me. I can download it (Thaehan - Last Letter).

**Comment by AKtomik** [comment]
> You don't need to remove the part after the "?".
> This doesn't work: 
> `down_on_spot.exe https://open.spotify.com/intl-de/track/2fXKyAyPrEa24c6PJyqznF?si=f35a831ebf024ec9`
> But this does:
> `down_on_spot.exe https://open.spotify.com/track/2fXKyAyPrEa24c6PJyqznF?si=f35a831ebf024ec9`
> Do you have a premium account?
> Your link works for me. I can download it (Thaehan - Last Letter).
> 

Hum, ok. That i do in the last send screenshoot (same link that you say its work for you), but does not work for me.
No, i dont have premium, probably for that its does not work on my side (and oSumAtrIX said that its a problem about difference between free and premium, so yep)

**Comment by oSumAtrIX** [comment]
It's an issue with aspotify as previously explained, you can attach a debugger and step into the code. At some point it where aspotify is used it will just crash. I'm in the middle of migrating to rspotify. The entire codebase needs to be refactored tbh

**Comment by zilpe** [comment]
@oSumAtrIX Did librespot patch free access? I am simply using free-librespot on it's own and it no longer works. Even after applying your modifications to the latest dev branch doesn't work either. Not sure what changed. Potentially sever side? Thanks

**Comment by oSumAtrIX** [comment]
The one field that I spoofed they spoofed themselves now, the fork is reduntant. I am not sure if additional modifications are currently needed, though currently DownOnSpot fails somewhere along the lines of aspotify from what I have seen, not librespot

**Comment by zilpe** [comment]
Weird. Because your fork was working in April for me too, but now running it gives the "Premium account required" error.

**Comment by oSumAtrIX** [comment]
Upstream has made adjustments recently. You should see errors when trying to use librespot. Anyways offtopic

**Comment by AirOne01** [comment]
Is it possible that it might be an EOL issue? Because Windows.

**Comment by oSumAtrIX** [comment]
@AirOne01 Unsure, though one issue is that the crate Spotify is deprecated. I stepped into the code and figured out where the problem was, but no panics whatsoever; the application just exists, and even the debugger can not catch it. I have locally migrated to a superseding crate, but it's not fully done yet.

**Comment by AirOne01** [comment]
@oSumAtrIX May be because of the classic "the error is handled" and it's just not.

**Comment by oSumAtrIX** [comment]
My bad, I meant to say the crate "aspotify" not "Spotify".

**Comment by oSumAtrIX** [comment]
Should be fixed with 388736973582149a33c214f3634bb79644b13736.
