### ISSUE TITLE
Login failed: Authentication Error

### ISSUE THREAD

**Issue by re11ding** [oSumAtrIX/DownOnSpot#54]
Login failed, possibly due to invalid credentials or settings: Authentication Error

I'm currently having issues using the application. While no information has changed, I can no longer log into spotify with a premium account. I simply get the error above. Earlier this year, this issue did not exist. I checked the api stuff, nothing changed there. I also generated a new client id and secret id, that didn't work either. I even deleted the settings.json, let it recreate, and refilled the information. Still no luck.

The username and password are correct as I can log into spotify with the same information. I've no idea what's going on here. Is this an isolated issue only to me or is the whole application not working now? I don't have another account to test it with.

**Comment by re11ding** [comment]
Never mind! I needed to build an updated version, my bad!

**Comment by oSumAtrIX** [comment]
#53
