### ISSUE TITLE
Create a folder for album

### ISSUE THREAD

**Issue by ckcr4lyf** [oSumAtrIX/DownOnSpot#60]
When downloading an album, it basically just fetches all tracks and then feeds them into the track downloader, dumping all to `downloads/`

It would be nice if it could auto make subfolders with either Artists / Album name (kinda like what deemix would do).

Would yoube open to such a PR? I could work on this feature (I'll probably implement it for my personal use anyway)

**Comment by oSumAtrIX** [comment]
See https://github.com/oSumAtrIX/DownOnSpot?tab=readme-ov-file#template-variables
