### ISSUE TITLE
Running downonspot.exe is giving (os error 10060)

### ISSUE THREAD

**Issue by eatkd** [oSumAtrIX/DownOnSpot#62]
**Describe the bug**
I am using windows 10 and installed rust as the readme said and build with the cargo, it successfully generated the downonspot.exe with one warning and then I filled the setting.json but when I run the downonspot.exe it is giving me os error 10060

**Screenshots**
![Screenshot 2023-09-07 134448](https://github.com/oSumAtrIX/DownOnSpot/assets/72932648/c46747ce-f08c-4410-b011-153ccad5e65a)

**Comment by oSumAtrIX** [comment]
Still happens?

**Comment by eatkd** [comment]
> Still happens?

Yes

**Comment by oSumAtrIX** [comment]
Try on another device and as admin

**Comment by eatkd** [comment]
Ok I managed to make it work on my windows pc, it was an issue with my internet and the .exe worked just fine with my hotspot.

**Comment by eatkd** [comment]
But now I have a seperate issue (exactly like this one https://github.com/oSumAtrIX/DownOnSpot/issues/53) but only with some podcasts ( eg. https://open.spotify.com/episode/6NoUD2da1TgL6QYMUZxV45?si=ba3683b803364934).
