### ISSUE TITLE
Doesn’t compile on MacOS with lame installed

### ISSUE THREAD

**Issue by iguesspaul** [oSumAtrIX/DownOnSpot#63]
**Describe the bug**
After running
```cargo build —release```
It returns the error 
```ld: library not found for -lmp3lame clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**To Reproduce**

1. Follow the installation instructions upto building
2. Run ```cargo build —release```

**Expected behavior**
I had run into this error, checked the readme and realized that I needed to install lame. I did, using homebrew. It installed successfully and the command works when I run it. So, I built the project again but it still failed. 

**Screenshots**
![Screenshot 2023-09-17 at 10 44 22](https://github.com/oSumAtrIX/DownOnSpot/assets/71736330/d2e2e8b7-e9cd-4950-b834-e8efd830547f)
![Screenshot 2023-09-17 at 10 44 35](https://github.com/oSumAtrIX/DownOnSpot/assets/71736330/42a7062a-a6db-4baa-acb0-16b8054b337d)
![Screenshot 2023-09-17 at 10 45 07](https://github.com/oSumAtrIX/DownOnSpot/assets/71736330/36414bc0-6f1f-479b-9a75-1eb8f923394e)

**Desktop (please complete the following information):**

- OS: macOs Ventura 13.4 on Apple M2
**Additional context**

**Comment by oSumAtrIX** [comment]
Is the library present in `/usr/local/lib/libmp3lame.dylib`? If so, for some reason the `/usr/local/lib` directory is not added to the library search path. You can try running `RUSTFLAGS="-L /usr/local/lib" cargo build --release` in this case.

**Comment by asapsmc** [comment]
I'm using MacOS 14.5 with Apple Silicon (M1) and I can't compile. I'm running with `RUSTFLAGS="-L /opt/homebrew/Cellar/lame/3.100/lib" cargo build --release` but I'm getting the following errors:
```
Updating crates.io index
    Updating git repository `ssh://git@github.com/oSumAtrIX/free-librespot.git`
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: failed to get `librespot` as a dependency of package `down_on_spot v0.5.1 (/Users/USER/Downloads/DownOnSpot)`

Caused by:
  failed to load source for dependency `librespot`

Caused by:
  Unable to update ssh://git@github.com/oSumAtrIX/free-librespot.git#f28fa264

Caused by:
  failed to fetch into: /Users/USER/.cargo/git/db/free-librespot-257f6fd081e0ebd3

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok 'ssh://git@github.com/oSumAtrIX/free-librespot.git' '+f28fa264528dc85f8f325c18e8461b0f2b43dca1:refs/commit/f28fa264528dc85f8f325c18e8461b0f2b43dca1'` (exit status: 128)
```
Using `cargo 1.80.1 (376290515 2024-07-16)`

**Comment by oSumAtrIX** [comment]
You don't have access to the repository mentioned there. Did you properly authenticate?

**Comment by asapsmc** [comment]
I'm having difficulties in following the readme instructions. So, I'm a spotify premium subscriber and I have now brew installed librespot (at `/usr/local/bin/librespot`). in Cargo.toml I have replaced `librespot = { git = "ssh://git@github.com/oSumAtrIX/free-librespot.git" }`by `librespot = { path = "/usr/local/bin/librespot" }`. However, I'm still getting errors: `cargo build --release
cd DownOnSpot
    Updating crates.io index
error: failed to get `librespot` as a dependency of package `down_on_spot v0.5.1 (/Users/USER/DownOnSpot)`

Caused by:
  failed to load source for dependency `librespot`

Caused by:
  Unable to update /usr/local/bin/librespot

Caused by:
  failed to read `/usr/local/bin/librespot/Cargo.toml`

Caused by:
  Not a directory (os error 20)
cd: no such file or directory: DownOnSpot`. Note: I'm using a regular Mac now (not the M1).

**Comment by oSumAtrIX** [comment]
Look what it said and what you replaced the line with:

![Screenshot_20240822-175222](https://github.com/user-attachments/assets/1df82c76-a7e6-40b5-a738-f35490c3ee75)

**Comment by asapsmc** [comment]
Sorry, I mis-explained. I had already tried that and got the following:
```
error: failed to parse manifest at `/Users/USER/DownOnSpot/Cargo.toml`

Caused by:
  dependency (librespot) specified without providing a local path, Git repository, version, or workspace dependency to use

```
That's why I tried with indicating the path directly.

**Comment by oSumAtrIX** [comment]
Seems like the readme is a bit unclear. You need to replace the entire line with `librespot = "0.4.2"`

**Comment by asapsmc** [comment]
That was it, now it worked. Thank you.

**Comment by asapsmc** [comment]
I also tried to redo `cargo build --release`, but now I'm getting error: 

```
failed to parse manifest at `/Users/USER/Cargo.toml`
Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present
```
Something went wrong with my installation, I suppose.
