### ISSUE TITLE
Error: Invalid state { invalid digit found in string } when trying to download

### ISSUE THREAD

**Issue by Edison12300** [oSumAtrIX/DownOnSpot#67]
Whenever I try to download a song, it shows "Error: Invalid state { invalid digit found in string }"

<img width="386" alt="image" src="https://github.com/oSumAtrIX/DownOnSpot/assets/71360570/5882f037-c02a-44cc-abf0-f1088bb80e1c">

**Comment by LostXOR** [comment]
This is also happening for me on Linux with Spotify Premium.

**Comment by ncc-hyperion** [comment]
Same issue for me!

**Comment by PEERSOFTdev** [comment]
Same for me.
Steps to reproduce:
1. In Ubuntu in WSL on the command line, I enter:
`rip https://open.spotify.com/track/3jkYFXONdX1Hi1swn6ao75`
where `rip` is an alias.
2. The output looks like this:
```
Settings successfully loaded.                                                                                                        
Continuing with spotify account: peer.gustavsson.                                                                                    
Login succeeded.                                                                                                                     
Preparing...       | The Days of Pearly Spencer                                                                                      
                                                                                                                                     
Elapsed second(s): 0                                                                                                                 
Error: Invalid state { invalid digit found in string } | The Days of Pearly Spencer                                                  
Finished download(s) in 1 second(s). 
```

**Comment by Christof93** [comment]
It can be fixed by using the newest version of librespot. (Change rev to `c491f90e09d6468829f004605fe14121a01c6674` in Cargo.toml)

**Comment by Edison12300** [comment]
> It can be fixed by using the newest version of librespot. (Change rev to `c491f90e09d6468829f004605fe14121a01c6674` in Cargo.toml)

Thanks!! It works now.

**Comment by LostXOR** [comment]
You should make a PR to update the version of librespot.

**Comment by oSumAtrIX** [comment]
Last version is Jul 29, 2022
