### ISSUE TITLE
Cargo Build on Ubuntu 22.04: `failed to run custom build for command alsa-sys v0.3.1`

### ISSUE THREAD

**Issue by ebb-earl-co** [oSumAtrIX/DownOnSpot#69]
**Describe the bug**
I am running Pop!_OS 22.04 and `cargo` 1.74.0, installed. Upon cloning the repository, I changed the `free-librespot` line in `Cargo.toml` as mentioned in the README.md. However, upon trying to build the project with `cargo build --release`, I ran into the following exception:

```bash
error: could not find system library 'alsa' required by the 'alsa-sys' crate
```

**To Reproduce**

1. Clone DownOnSpot to a user-writable directory
2. Edit `Cargo.toml` to replace `"ssh://git@github.com/oSumAtrIX/free-librespot.git"` with `librespot = "0.4.2"`
3. Using `cargo` version 1.74.0, run `cargo build --release` from just-cloned directory root

**Expected behavior**
I expected to hit the `[libmp3lame](https://www.rarewares.org/mp3-lame-libraries.php#libmp3lame)` error mentioned in the doc, because I know that I don't have that library installed. However, I was not expecting to get an error to do with ALSA, as Pop!_OS 22.04 ships with `pipewire-alsa` by default (or, at least, it was installed before attemping `cargo build --release`).

**Screenshots**
![Screenshot from 2023-12-02 22-25-33](https://github.com/oSumAtrIX/DownOnSpot/assets/11299014/8722c23e-3a37-44ae-a41f-122197057a1a)

**Desktop (please complete the following information):**

- OS: Pop!_OS 22.04
- Rust: `rustc 1.74.0 (79e9716c9 2023-11-13)` and `cargo 1.74.0 (ecb9851af 2023-10-18)`

**Additional context**
After search engine-ing the error, I came across the `spotifyd` project, and in a GitHub issue for that project [was the answer I needed](https://github.com/Spotifyd/spotifyd/issues/659#issuecomment-737730954). It turns out that the `librust-alsa-sys-dev` package was necessary from APT.
*HOWEVER*
once I installed the aforementioned ALSA-related package, upon trying `cargo build --release` again, I hit an error to do with `libmp3lame`:
![Screenshot from 2023-12-02 22-30-06](https://github.com/oSumAtrIX/DownOnSpot/assets/11299014/5a98c88e-14c7-4b60-b0a4-63e781457146)

Even though I have `libmp3lame0` installed,
```bash
libmp3lame0 3.100-3build2 [Ubuntu/jammy main]
├── is installed
└── MP3 encoding library
```
it turns out that I needed *`libmp3lame-dev`* in order to successfully compile. Once I installed `libmp3lame-dev`, the `cargo build --release` command exited successfully!

Maybe these steps would be useful in the README.md, in order to help others with Ubuntu-like OSes. Thanks for the project!

**Comment by oSumAtrIX** [comment]
The crate that fails to build expects system libraries to be present. The official documentstion mentions a different package: https://github.com/diwic/alsa-sys

Can you confirm if this solves the issue?

**Comment by LeoColman** [comment]
I was having the same issue and can confirm that running

`sudo apt install libasound2-dev`

on Ubuntu 22.04 fixed the issue for me

**Comment by ebb-earl-co** [comment]
@oSumAtrIX as I said at the end of the original issue, installing `librust-alsa-sys-dev` was sufficient to build on Ubuntu. I was just hoping to add helpful information to the README by working out the problem and making it an issue here.

**Comment by oSumAtrIX** [comment]
It is not the correct library and just happened to work, likely due to the correct library being a dependency @LeoColman has already answered.

**Comment by WMP** [comment]
For my 220.04 this is all dependeny: `apt install cargo libmp3lame-dev pkg-config libssl-dev libasound2-dev`
