### ISSUE TITLE
Downloading song fails: Channel error

### ISSUE THREAD

**Issue by onny** [oSumAtrIX/DownOnSpot#7]
Hey,
sometimes I get following error message:
```
Channel Error      | Rolling Moon
Finished download(s) in 20 second(s).
```
When I try the download again, it succeeds and the missing file was downloaded correctly.
Maybe DownOnSpot should try downloading again 2-3 times.

Regards
Jonas

**Comment by oSumAtrIX** [comment]
Can you add reproduction steps?
