### ISSUE TITLE
Unable to download tracks

### ISSUE THREAD

**Issue by emtprt** [oSumAtrIX/DownOnSpot#73]
**Describe the bug**
For every track (except of reported as "Unavailable") I receive "Error: Invalid state { invalid digit found in string }" regardless it is an individual track link or a playlist 

**To Reproduce**
Appears immediately after "Preparing" step.

**Desktop (please complete the following information):**

- OS: Linux Mint 21.3, fresh build from latest sources
- Tried to refresh dev key, no changes

**Additional context**
I'm not a rust guy, but as far I might guess from sources, it might come from librespot and, probably, could be the consequence spotify api changes, that are being discussed [here](https://github.com/librespot-org/librespot/pull/1220)

**Comment by oSumAtrIX** [comment]
I am unable to reproduce this issue on my end.

**Comment by ckcr4lyf** [comment]
> For every track (except of reported as "Unavailable") I receive "Error: Invalid state { invalid digit found in string }" regardless it is an individual track link or a playlist

I noticed this issue a few weeks ago, turns out it was just due to my DownOnSpot being very old. On the latest master, using "official" librespot, it seems to work fine. on my end.

**Comment by oSumAtrIX** [comment]
The fork I use was updated 3 months ago, whereas the commit of librespot was a month ago. I am not sure if there was a commit in that timespan that fixes this issue, but I can not reproduce it. A git bisect should give more insight
