### ISSUE TITLE
Compiling on MacOS 14.2.1 with Apple Silicon (M1) fails

### ISSUE THREAD

**Issue by babblecatproduction** [oSumAtrIX/DownOnSpot#78]
When I try to compile using `cargo build --release` I get these error(s):

>    Compiling down_on_spot v0.2.6 (/Users/USER/DownOnSpot)
> **error: linking with `cc` failed: exit status: 1**
>   |
>   = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/USER/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/USER/miniconda3/bin:/Users/USER/miniconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/USER/.cargo/bin:/Users/USER/.local/bin:/Users/USER/.local/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/62/ymm9l02j71g8jlcyvz86zbn40000gn/T/rustcxrQMRj/symbols.o" "/Users/USER/DownOnSpot/target/release/deps/down_on_spot-ef63166852dc802d.down_on_spot.62612945f50140c2-cgu.0.rcgu.o" "-L" "/Users/USER/DownOnSpot/target/release/deps" "-L" "/Users/USER/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/USER/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-4010f8e9d1f7f9aa.rlib" "-lmp3lame" "-framework" "SystemConfiguration" "-framework" "Security" "-framework" "AudioUnit" "-framework" "CoreAudio" "-framework" "CoreFoundation" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/USER/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/USER/DownOnSpot/target/release/deps/down_on_spot-ef63166852dc802d" "-Wl,-dead_strip" "-nodefaultlibs"
>   = **note: ld: library 'mp3lame' not found**
>           clang: error: linker command failed with exit code 1 (use -v to see invocation)
>           
> 
> error: could not compile `down_on_spot` (bin "down_on_spot") due to 1 previous error

I installed Lame via Brew and edited the Cargo.toml file (replaced git = "ssh://git@github.com/oSumAtrIX/free-librespot.git" with librespot = "0.4.2").

**Comment by oSumAtrIX** [comment]
check https://github.com/oSumAtrIX/DownOnSpot/issues/63#issuecomment-1744341716
