### ISSUE TITLE
It does not work with **Free** Spotify accounts (Is it supposed or not?)

### ISSUE THREAD

**Issue by luca-mazzola** [oSumAtrIX/DownOnSpot#79]
**Describe the bug**
AS indicated in the README.md, I was trying the current release with a **FREE** Spotify account (after setting the quality level to 160) but it seems not to work.

**To Reproduce**
1. Clone the current repository (April 08, 2024)
2. Install the ssh key for the repository "free_librespot"
3. cargo build (successfully terminated)
4. launching the build with a spotify track URL (eg: https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g)
5. see error message: "Login failed, possibly due to invalid credentials or settings: Authentication Error"

**Expected behavior**

**Screenshots**
![Screenshot from 2024-04-09 06-25-46](https://github.com/oSumAtrIX/DownOnSpot/assets/48471452/6139495c-0ce7-4ba7-8da4-559ff795e90f)

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04.6 LTS

**Additional context**
Tested the account (username and pwd) and the Spotify APP with direct request on the Spotify APIs from a pythons script, and it works. 
Is this project suppose to work with free Spotify accounts or not?
Is there any way to produce a more detailed debug, so to maybe understand the root cause of this error?

**Comment by oSumAtrIX** [comment]
The project is supposed to work on a free account, I'll investigate.

**Comment by oSumAtrIX** [comment]
That's odd, it works on my end:

<img width="545" alt="image" src="https://github.com/oSumAtrIX/DownOnSpot/assets/13122796/f0af2ae6-9b5a-4836-bbee-c1535b6434f9">

**Comment by oSumAtrIX** [comment]
Oh, I can see your error. Try your e-mail instead of your username; I can see how confused you are.

**Comment by mbjd05** [comment]
The repository for the custom version of librespot needed for use with free accounts does not exist anymore: [https://github.com/oSumAtrIX/free-librespot](https://github.com/oSumAtrIX/free-librespot)

**Comment by oSumAtrIX** [comment]
Reopen if still an issue.
