### ISSUE TITLE
Template variables in path not being replaced with their values

### ISSUE THREAD

**Issue by ashzw** [oSumAtrIX/DownOnSpot#8]
Basically the title. Setting the path as `C:/Users/[user]/Downloads/%albumArtist%/%album%`, for example, creates two folders, literally named "%albumArtist%" and "%album%".

Your README mentions that template variables are available in the path. Or am I using it wrong?

**Comment by oSumAtrIX** [comment]
Are you on the latest commit? Run the command `git pull` in the root folder of the repository to fetch and apply the latest commits.

**Comment by ashzw** [comment]
Thank you! I wasn't on the latest commit. Now it's working perfectly :)
