### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by onny** [oSumAtrIX/DownOnSpot#92]
Would really like to see a release tag for the project, so we won't have to package unstable releases

**Comment by oSumAtrIX** [comment]
Usually, I use semantic release, and even though it's meant for libraries with a public API I just ignore that part of the spec (major version) or interpret the CLI as the public API. If there's semantic-release for cargo, we can set up a dev and main branch. Semantic-release will create prereleases for dev and on commits to main (merging dev to main) full releases

**Comment by oSumAtrIX** [comment]
https://github.com/oSumAtrIX/DownOnSpot/releases/tag/v0.5.0 Thanks for the suggestion
